export const features = [
  {
    key: 'patent-search',
    title: 'Patent Search',
    description: 'AI-powered patent search across global databases with intelligent query expansion and relevance ranking.',
    icon: '🔍',
    color: '#667eea',
    apiPath: '/patent-search',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'technology_area', label: 'Technology' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'results_count', label: 'Results' },
    ],
    fields: [
      { key: 'title', label: 'Search Title', type: 'text', required: true },
      { key: 'query', label: 'Search Query', type: 'textarea', required: true },
      { key: 'technology_area', label: 'Technology Area', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['title', 'query', 'technology_area', 'status', 'results_count', 'description'],
    aiPromptLabel: 'Describe the technology or invention to search for',
  },
  {
    key: 'prior-art',
    title: 'Prior Art Analysis',
    description: 'Discover relevant prior art references and assess patentability with AI-driven analysis.',
    icon: '📚',
    color: '#764ba2',
    apiPath: '/prior-art',
    columns: [
      { key: 'invention_title', label: 'Invention' },
      { key: 'technology_field', label: 'Field' },
      { key: 'novelty_score', label: 'Novelty', type: 'score' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'invention_title', label: 'Invention Title', type: 'text', required: true },
      { key: 'invention_description', label: 'Invention Description', type: 'textarea', required: true },
      { key: 'technology_field', label: 'Technology Field', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['invention_title', 'invention_description', 'technology_field', 'status', 'novelty_score', 'references_found', 'analysis_result'],
    aiPromptLabel: 'Describe the invention for prior art analysis',
  },
  {
    key: 'patent-drafting',
    title: 'Patent Drafting',
    description: 'AI-assisted patent application drafting with proper legal language and comprehensive specifications.',
    icon: '📝',
    color: '#f093fb',
    apiPath: '/patent-drafting',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'technical_field', label: 'Field' },
      { key: 'inventors', label: 'Inventors' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'title', label: 'Patent Title', type: 'text', required: true },
      { key: 'invention_summary', label: 'Invention Summary', type: 'textarea', required: true },
      { key: 'technical_field', label: 'Technical Field', type: 'text' },
      { key: 'inventors', label: 'Inventors', type: 'text' },
      { key: 'abstract', label: 'Abstract', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'review', 'filed', 'approved'] },
    ],
    detailFields: ['title', 'invention_summary', 'technical_field', 'status', 'inventors', 'abstract', 'description'],
    aiPromptLabel: 'Describe the invention to draft a patent application',
  },
  {
    key: 'claims-generator',
    title: 'Claims Generator',
    description: 'Generate strategic patent claims with proper hierarchy, broad protection, and legal precision.',
    icon: '⚖️',
    color: '#4facfe',
    apiPath: '/claims-generator',
    columns: [
      { key: 'patent_title', label: 'Patent' },
      { key: 'claim_type', label: 'Type' },
      { key: 'num_independent', label: 'Independent' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'invention_description', label: 'Invention Description', type: 'textarea', required: true },
      { key: 'claim_type', label: 'Claim Type', type: 'select', options: ['Method', 'System', 'Apparatus', 'Composition'] },
      { key: 'num_independent', label: 'Independent Claims', type: 'number' },
      { key: 'num_dependent', label: 'Dependent Claims', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'review', 'approved'] },
    ],
    detailFields: ['patent_title', 'invention_description', 'claim_type', 'num_independent', 'num_dependent', 'claims_text', 'status'],
    aiPromptLabel: 'Describe the invention to generate patent claims',
  },
  {
    key: 'classification',
    title: 'Patent Classification',
    description: 'Automatically classify patents using IPC and CPC codes with AI-powered accuracy.',
    icon: '🏷️',
    color: '#00f2fe',
    apiPath: '/classification',
    columns: [
      { key: 'patent_title', label: 'Patent' },
      { key: 'technology_sector', label: 'Sector' },
      { key: 'confidence_score', label: 'Confidence', type: 'score' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea', required: true },
      { key: 'technology_sector', label: 'Technology Sector', type: 'text' },
      { key: 'ipc_codes', label: 'IPC Codes', type: 'text' },
      { key: 'cpc_codes', label: 'CPC Codes', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'classified', 'verified'] },
    ],
    detailFields: ['patent_title', 'description', 'technology_sector', 'ipc_codes', 'cpc_codes', 'confidence_score', 'status'],
    aiPromptLabel: 'Describe the invention to classify with IPC/CPC codes',
  },
  {
    key: 'infringement',
    title: 'Infringement Analysis',
    description: 'AI-powered claim-by-claim infringement analysis with risk assessment and mapping.',
    icon: '🛡️',
    color: '#fc8181',
    apiPath: '/infringement',
    columns: [
      { key: 'patent_number', label: 'Patent #' },
      { key: 'accused_product', label: 'Accused Product' },
      { key: 'risk_level', label: 'Risk', type: 'badge' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'patent_number', label: 'Patent Number', type: 'text', required: true },
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'accused_product', label: 'Accused Product', type: 'text', required: true },
      { key: 'analysis_type', label: 'Analysis Type', type: 'select', options: ['Literal', 'Equivalents', 'Combined'] },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'claim_mapping', label: 'Claim Mapping', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['patent_number', 'patent_title', 'accused_product', 'analysis_type', 'risk_level', 'claim_mapping', 'status'],
    aiPromptLabel: 'Describe the patent and product for infringement analysis',
  },
  {
    key: 'valuation',
    title: 'Patent Valuation',
    description: 'Estimate patent values using cost, market, and income approaches with AI analysis.',
    icon: '💰',
    color: '#48bb78',
    apiPath: '/valuation',
    columns: [
      { key: 'patent_number', label: 'Patent #' },
      { key: 'patent_title', label: 'Title' },
      { key: 'estimated_value', label: 'Value' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'patent_number', label: 'Patent Number', type: 'text', required: true },
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'technology_area', label: 'Technology Area', type: 'text' },
      { key: 'valuation_method', label: 'Method', type: 'select', options: ['Income', 'Market', 'Cost'] },
      { key: 'estimated_value', label: 'Estimated Value', type: 'text' },
      { key: 'market_size', label: 'Market Size', type: 'text' },
      { key: 'remaining_life', label: 'Remaining Life (years)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['patent_number', 'patent_title', 'technology_area', 'valuation_method', 'estimated_value', 'market_size', 'remaining_life', 'status'],
    aiPromptLabel: 'Describe the patent for valuation analysis',
  },
  {
    key: 'portfolio',
    title: 'Portfolio Analytics',
    description: 'Analyze patent portfolios for strength, coverage, and strategic optimization opportunities.',
    icon: '📊',
    color: '#ed8936',
    apiPath: '/portfolio',
    columns: [
      { key: 'portfolio_name', label: 'Portfolio' },
      { key: 'owner', label: 'Owner' },
      { key: 'total_patents', label: 'Patents' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'portfolio_name', label: 'Portfolio Name', type: 'text', required: true },
      { key: 'owner', label: 'Owner', type: 'text', required: true },
      { key: 'total_patents', label: 'Total Patents', type: 'number' },
      { key: 'technology_areas', label: 'Technology Areas', type: 'textarea' },
      { key: 'total_value', label: 'Total Value', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'review', 'archived'] },
    ],
    detailFields: ['portfolio_name', 'owner', 'total_patents', 'technology_areas', 'total_value', 'strength_score', 'status', 'description'],
    aiPromptLabel: 'Describe the patent portfolio for analysis',
  },
  {
    key: 'competitor',
    title: 'Competitor Monitoring',
    description: 'Track and analyze competitor patent activities with AI-driven competitive intelligence.',
    icon: '👁️',
    color: '#9f7aea',
    apiPath: '/competitor',
    columns: [
      { key: 'competitor_name', label: 'Competitor' },
      { key: 'technology_area', label: 'Technology' },
      { key: 'recent_filings', label: 'Filings' },
      { key: 'threat_level', label: 'Threat', type: 'badge' },
    ],
    fields: [
      { key: 'competitor_name', label: 'Competitor Name', type: 'text', required: true },
      { key: 'technology_area', label: 'Technology Area', type: 'text' },
      { key: 'recent_filings', label: 'Recent Filings', type: 'number' },
      { key: 'threat_level', label: 'Threat Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'key_patents', label: 'Key Patents', type: 'textarea' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'monitoring_status', label: 'Status', type: 'select', options: ['active', 'paused', 'archived'] },
    ],
    detailFields: ['competitor_name', 'technology_area', 'recent_filings', 'threat_level', 'key_patents', 'monitoring_status', 'notes'],
    aiPromptLabel: 'Describe the competitor to analyze their patent strategy',
  },
  {
    key: 'filing',
    title: 'Filing Management',
    description: 'Manage patent filings across jurisdictions with deadline tracking and cost estimation.',
    icon: '📋',
    color: '#38b2ac',
    apiPath: '/filing',
    columns: [
      { key: 'application_title', label: 'Application' },
      { key: 'jurisdiction', label: 'Jurisdiction' },
      { key: 'filing_type', label: 'Type' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'application_title', label: 'Application Title', type: 'text', required: true },
      { key: 'application_number', label: 'Application Number', type: 'text' },
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'text', required: true },
      { key: 'filing_type', label: 'Filing Type', type: 'select', options: ['Utility', 'PCT', 'Provisional', 'Design', 'National', 'European Patent', 'Patent', 'Standard Patent', 'Invention'] },
      { key: 'attorney', label: 'Attorney', type: 'text' },
      { key: 'estimated_cost', label: 'Estimated Cost', type: 'text' },
      { key: 'filing_date', label: 'Filing Date', type: 'text' },
      { key: 'deadline', label: 'Deadline', type: 'text' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['preparing', 'filed', 'examination', 'allowed', 'granted', 'abandoned'] },
    ],
    detailFields: ['application_title', 'application_number', 'jurisdiction', 'filing_type', 'status', 'attorney', 'estimated_cost', 'filing_date', 'deadline', 'notes'],
    aiPromptLabel: 'Describe the filing for strategy recommendations',
  },
  {
    key: 'citation',
    title: 'Citation Analysis',
    description: 'Analyze patent citation networks, influence metrics, and citation-based quality scores.',
    icon: '🔗',
    color: '#e53e3e',
    apiPath: '/citation',
    columns: [
      { key: 'patent_number', label: 'Patent #' },
      { key: 'patent_title', label: 'Title' },
      { key: 'forward_citations', label: 'Forward' },
      { key: 'citation_score', label: 'Score', type: 'score' },
    ],
    fields: [
      { key: 'patent_number', label: 'Patent Number', type: 'text', required: true },
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'forward_citations', label: 'Forward Citations', type: 'number' },
      { key: 'backward_citations', label: 'Backward Citations', type: 'number' },
      { key: 'influential_citations', label: 'Influential Citations', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['patent_number', 'patent_title', 'forward_citations', 'backward_citations', 'citation_score', 'influential_citations', 'status'],
    aiPromptLabel: 'Enter patent number or title for citation analysis',
  },
  {
    key: 'translation',
    title: 'Patent Translation',
    description: 'AI-powered patent translation maintaining legal precision and technical accuracy.',
    icon: '🌐',
    color: '#3182ce',
    apiPath: '/translation',
    columns: [
      { key: 'patent_title', label: 'Patent' },
      { key: 'source_language', label: 'From' },
      { key: 'target_language', label: 'To' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'source_language', label: 'Source Language', type: 'select', options: ['English', 'Chinese', 'Japanese', 'Korean', 'German', 'French', 'Spanish'], required: true },
      { key: 'target_language', label: 'Target Language', type: 'select', options: ['English', 'Chinese', 'Japanese', 'Korean', 'German', 'French', 'Spanish'], required: true },
      { key: 'original_text', label: 'Original Text', type: 'textarea', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['patent_title', 'source_language', 'target_language', 'original_text', 'translated_text', 'word_count', 'status'],
    aiPromptLabel: 'Enter text to translate with source and target languages',
  },
  {
    key: 'landscape',
    title: 'Landscape Analysis',
    description: 'Map technology landscapes, identify white spaces, and track innovation trends.',
    icon: '🗺️',
    color: '#d69e2e',
    apiPath: '/landscape',
    columns: [
      { key: 'technology_area', label: 'Technology' },
      { key: 'scope', label: 'Scope' },
      { key: 'total_patents_analyzed', label: 'Patents' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'technology_area', label: 'Technology Area', type: 'text', required: true },
      { key: 'scope', label: 'Geographic Scope', type: 'text' },
      { key: 'time_period', label: 'Time Period', type: 'text' },
      { key: 'total_patents_analyzed', label: 'Patents Analyzed', type: 'number' },
      { key: 'key_players', label: 'Key Players', type: 'textarea' },
      { key: 'white_spaces', label: 'White Spaces', type: 'textarea' },
      { key: 'trends', label: 'Trends', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed'] },
    ],
    detailFields: ['technology_area', 'scope', 'time_period', 'total_patents_analyzed', 'key_players', 'white_spaces', 'trends', 'status'],
    aiPromptLabel: 'Describe the technology area for landscape analysis',
  },
  {
    key: 'renewal',
    title: 'Renewal Tracking',
    description: 'Track patent renewal deadlines, manage fees, and optimize maintenance strategies.',
    icon: '🔄',
    color: '#dd6b20',
    apiPath: '/renewal',
    columns: [
      { key: 'patent_number', label: 'Patent #' },
      { key: 'patent_title', label: 'Title' },
      { key: 'renewal_date', label: 'Due Date' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'patent_number', label: 'Patent Number', type: 'text', required: true },
      { key: 'patent_title', label: 'Patent Title', type: 'text', required: true },
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'text' },
      { key: 'renewal_date', label: 'Renewal Date', type: 'text' },
      { key: 'renewal_fee', label: 'Renewal Fee', type: 'text' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'auto_renew', label: 'Auto Renew', type: 'select', options: ['true', 'false'] },
      { key: 'notes', label: 'Notes', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['upcoming', 'overdue', 'renewed', 'abandoned'] },
    ],
    detailFields: ['patent_number', 'patent_title', 'jurisdiction', 'renewal_date', 'renewal_fee', 'status', 'priority', 'auto_renew', 'notes'],
    aiPromptLabel: 'Describe the patent for renewal strategy recommendations',
  },
  {
    key: 'collaboration',
    title: 'Collaboration Hub',
    description: 'Coordinate patent work between inventors, attorneys, and stakeholders efficiently.',
    icon: '👥',
    color: '#805ad5',
    apiPath: '/collaboration',
    columns: [
      { key: 'title', label: 'Task' },
      { key: 'assigned_to', label: 'Assigned To' },
      { key: 'priority', label: 'Priority', type: 'badge' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    fields: [
      { key: 'title', label: 'Task Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'assigned_to', label: 'Assigned To', type: 'text' },
      { key: 'task_type', label: 'Task Type', type: 'select', options: ['Review', 'Research', 'Filing', 'Legal', 'Analytics', 'Invention Disclosure', 'Monitoring', 'Valuation', 'Administrative'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'due_date', label: 'Due Date', type: 'text' },
      { key: 'patent_reference', label: 'Patent Reference', type: 'text' },
      { key: 'comments', label: 'Comments', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'in_progress', 'review', 'completed', 'blocked'] },
    ],
    detailFields: ['title', 'description', 'assigned_to', 'task_type', 'priority', 'status', 'due_date', 'patent_reference', 'comments'],
    aiPromptLabel: 'Describe the task for AI collaboration suggestions',
  },
];

export function getFeature(key) {
  return features.find(f => f.key === key);
}

export function getBadgeClass(value) {
  const v = String(value).toLowerCase();
  if (['completed', 'active', 'approved', 'granted', 'renewed', 'classified', 'allowed'].includes(v)) return 'badge-success';
  if (['in_progress', 'review', 'examination', 'upcoming', 'medium', 'growing'].includes(v)) return 'badge-warning';
  if (['critical', 'overdue', 'high', 'blocked', 'abandoned'].includes(v)) return 'badge-danger';
  if (['filed', 'draft', 'open', 'preparing', 'pending'].includes(v)) return 'badge-info';
  if (['low', 'paused', 'verified'].includes(v)) return 'badge-primary';
  return 'badge-info';
}
